# Generated by Django 6.0.3 on 2026-03-11 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProctorSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_type', models.CharField(choices=[('webcam', 'Webcam'), ('screen', 'Screen')], default='webcam', max_length=10)),
                ('image_data', models.TextField()),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('flag_reason', models.CharField(blank=True, max_length=200)),
                ('student_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='Examapp.studentexam')),
            ],
            options={
                'ordering': ['captured_at'],
            },
        ),
    ]
