# Generated by Django 6.0.3 on 2026-04-04 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examapp', '0004_studentproxy_teacherproxy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('true_false', 'True/False'), ('short_answer', 'Short Answer'), ('coding', 'Coding (C)')], max_length=20),
        ),
        migrations.CreateModel(
            name='CodingTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stdin', models.TextField(blank=True)),
                ('expected_output', models.TextField()),
                ('marks', models.IntegerField(default=1)),
                ('is_hidden', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='Examapp.question')),
            ],
            options={
                'ordering': ['question', 'order'],
            },
        ),
    ]
